#!/bin/bash

# This is a social network app that is developed for edX Unix course 
# Author: Amir Mir (s.a.m.mir@tudelft.nl)
# Date: May, 2020
# License: GNU General Public License v3.0

# shellcheck disable=SC1091
source "networks.sh";
source "posts.sh";
source "users.sh";

function rm_line_from_file() {
    # Removes a given line from a file.
    # $1: a line

    awk -v u="$1"  '{!/^u$/}' "$2" > "$(dirname "$2")/temp" && mv "$(dirname "$2")/temp" "$2";
}

function push_changes() {
    # Pushes recent changes to the Git server

    git add networks users;
    git commit -m "Updating social networks - $(date +"%y-%m-%d %r")";
    git push;
    printf "*******************************\n";
    printf "Successfully pushed recent changes to the server.\n";
}

function help() {
    # Shows the description of program's options for the user.

    echo "sn - A command-line based social network program for Unix systems (v0.1)"
    echo "Copyright (c) 2020, Amir M. Mir"
    echo
    echo "Options:"
    echo "create <name>     Create a new social network in the system."
    echo "join <name>       Join an existing social network in the system."
    echo "leave <name>      Leave an existing social network."
    echo "pull              Pull new social networks and posts."
    echo "log               Show a list of existing posts."
    echo "show <name>       Show a specified post."
    echo "post              Publish a new post."
    echo "like <name>       Like a specified post."
    echo "push              Push locally made changes back to the server."
    echo "members           Show the members of subscribed networks."
    echo "networks          Show a list of existing social networks in the system."
    echo "follow <name>     Follow a specified user."
    echo "unfollow <name>   Unfollow a specified user."
    echo "help              Show the description of program's options."
}

function main() {
    # The social app starts from here based on given options.

    if [[ $# -eq 0 ]]; then
        printf "No arguments passed.\npass help to see the avialable options.\n"
        exit 1
    else

        if ! check_user_exists; then
            create_user;
        fi

        # Finds existing posts at the time of running the social app.
        find_existing_posts;

        if [[ $1 = "create" ]]; then
            if check_network_exists "$2"; then
                printf "The network %s already exists!\n" "$2";
            else
                create_social_network "$2";
            fi
        elif [[ $1 = "join" ]]; then
            if check_network_exists "$2"; then
                join_social_network "$2";
            else
                printf "The network %s doesn't exist!\n" "$1"
            fi
        elif [[ $1 = "leave" ]]; then
            if check_network_exists "$2"; then
                leave_social_network "$2";
            else
                printf "The network %s doesn't exist!\n" "$1"
            fi
        elif [[ $1 = "pull" ]]; then
            printf "Pulling new posts and likes\n";
            git pull;
        elif [[ $1 = "log" ]]; then
            show_existing_posts;
        elif [[ $1 = "show" ]]; then
            show_post "$2" "1";
        elif [[ $1 = "post" ]]; then
            post_new_story;
        elif [[ $1 = "like" ]]; then
            like_post "$2";
        elif [[ $1 = "push" ]]; then 
            push_changes;
        elif [[ $1 = "members" ]]; then
            show_network_members;
        elif [[ $1 = 'networks' ]]; then
            show_existing_networks;
        elif [[ $1 = "follow" ]]; then
            follow_user "$2";
        elif [[ $1 = "unfollow" ]]; then
            unfollow_user "$2";
        elif [[ $1 = "help" ]]; then
            help;
        else
            printf "%s is not a recongnized command.\nUse help option to see the description of the available commands.\n" "$1"
        fi
    fi
}

#####################################################################

main "$@"